version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    expose: 
      - "8000"
  frontentd:
    depends_on:
      - backend
    build: './front_end'
    working_dir: /usr/app
    ports: 
      - "3000:3000"
    expose: 
      - "3000"
    stdin_open: true